name: main

on:
  push:
    branches:
     - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set config
      run: |
        echo "${{ secrets.GITEA_TOKEN }}" > ~/deploy_key.pem
        git config --local user.email "github@actions"
        git config --local user.name "github"
        git config remote.origin.url "ssh://git@git.trap.jp:2200/Chat-Yojo-Bot/gateway.git"
    - name: Push changes
      env:
        GIT_SSH_COMMAND: ssh -i ~/deploy_key.pem -o StrictHostKeyChecking=no -F /dev/null
      run: git push origin main