name: main

on:
  push:
    branches:
     - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set config
      run: |
        git config --local user.email "github@actions"
        git config --local user.name "github"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITEA_TOKEN }}
        branch: main
        repository: 'https://git.trap.jp/Chat-Yojo-Bot/gateway.git'